### ISSUE TITLE
Snake: warning spam

### ISSUE THREAD

**Issue by psobolewskiPhD** [haesleinhuepf/natari#3]
After launching the snake game, the following warning is spammed in the napari warning window and my terminal (Napari launched from terminal, not jupyter/vs code etc.)
```
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/jupyter_client/session.py:809: DeprecationWarning: Accessing zmq Socket attribute recv_multipart on BackgroundSocket!
```

**Comment by psobolewskiPhD** [comment]
Info below.
The warning spam is triggered on a loss condition: turning on self, hitting wall, snakes colliding. 

```
napari: 0.4.11
Platform: macOS-11.6-arm64-arm-64bit
System: MacOS 11.6
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- StarDist: 2021.6.28
- aicsimageio-in-memory: 0.4.1
- aicsimageio-out-of-memory: 0.4.1
- animation: 0.0.2
- clEsperanto: 0.10.2
- console: 0.0.4
- napari-tools-menu: 0.1.3
- natari: 0.2.3
- ome-types: 0.2.6
- scikit-image: 0.4.11
- svg: 0.1.5

```

**Comment by psobolewskiPhD** [comment]
Now that I can do the cell counting game, I get the same error spammed a dozen times there at start, but then it doesn't continue and everything is peachy.

**Comment by haesleinhuepf** [comment]
> ```
>python3.9/site-packages/jupyter_client/session.py:809: DeprecationWarning: Accessing zmq Socket
> ```

Ok, I have no real idea what might be the issue here: The error obviously comes from [project jupyter](https://github.com/jupyter) and [zero mq](https://github.com/zeromq). Natari uses neither of both.

Can you try updating zero-mq as suggested here?
* https://github.com/zeromq/cppzmq/issues/330#issuecomment-574857628

**Comment by psobolewskiPhD** [comment]
I updated `pyzmq` and `jupyter-client` but alas, no difference.
Not sure where the C libzmq could be located to even try to build that.

However! When I launch napari from VS Code Interactive Window or ipython then the issue goes away. The warning spam only happens when using the plugin after launching napari from my terminal shell using `napari`.
Very odd...

**Comment by psobolewskiPhD** [comment]
Not sure what did it, some change in my conda env or napari update or natari update, but the issue is gone whether launching from ipython or terminal.
